"""Updated translation model

Revision ID: 8c395250a215
Revises: c5c7ac0cc86b
Create Date: 2025-02-20 16:17:37.141935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision: str = '8c395250a215'
down_revision: Union[str, None] = 'c5c7ac0cc86b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def column_exists(connection, table_name: str, column_name: str) -> bool:
    inspector = Inspector.from_engine(connection)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade() -> None:
    connection = op.get_bind()
    if not column_exists(connection, 'translations', 'user_id'):
        # ### commands auto generated by Alembic - please adjust! ###
        op.add_column('translations', sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        op.create_foreign_key(None, 'translations', 'userdata', ['user_id'], ['user_id'])
        # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'translations', type_='foreignkey')
    op.drop_column('translations', 'user_id')
    # ### end Alembic commands ###
