"""Create tables

Revision ID: 20d2fc55f18a
Revises: 
Create Date: 2025-02-19 16:03:37.021198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '20d2fc55f18a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userdata',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('englishwordsdb',
    sa.Column('origin_word', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['userdata.user_id'], ),
    sa.PrimaryKeyConstraint('origin_word', 'user_id')
    )
    op.create_table('ukrainianwordsdb',
    sa.Column('origin_word', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['userdata.user_id'], ),
    sa.PrimaryKeyConstraint('origin_word', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ukrainianwordsdb')
    op.drop_table('englishwordsdb')
    op.drop_table('userdata')
    # ### end Alembic commands ###
