"""Add translatons

Revision ID: c5c7ac0cc86b
Revises: 20d2fc55f18a
Create Date: 2025-02-19 16:17:58.266538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision: str = 'c5c7ac0cc86b'
down_revision: Union[str, None] = '20d2fc55f18a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def table_exists(connection, table_name: str) -> bool:
    inspector = Inspector.from_engine(connection)
    return table_name in inspector.get_table_names()



def upgrade() -> None:
    connection = op.get_bind()

    if not table_exists(connection, 'translations'):
        # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('translations',
        sa.Column('origin_word', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('translation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint('origin_word', 'translation')
        )
        # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translations')
    # ### end Alembic commands ###
